apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-search
  description: Search API for the wayback machine
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/mickeysaxena/API-Mapping-Designer-Tool/blob/main/catalogue-info.yaml/openapi.yaml
